// Code generated by importer. DO NOT EDIT.
// Source: thirdy/jsonata/test/test-suite/groups/boolean-expresssions

package imported_test

import (
	"context"
	"testing"

	"github.com/sandrolain/gosonata/pkg/evaluator"
	"github.com/sandrolain/gosonata/pkg/parser"
)

// TestBooleanExpresssions runs 31 test cases from the official JSONata test suite.
// Group: boolean-expresssions
func TestBooleanExpresssions(t *testing.T) {
	testCases := []struct {
		name        string
		query       string
		data        interface{}
		bindings    map[string]interface{}
		expected    interface{}
		shouldError bool
		errorCode   string
	}{

		{
			name:  "case000",
			query: `true`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case001",
			query: `false`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case002",
			query: `false or false`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case003",
			query: `false or true`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case004",
			query: `true or false`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case005",
			query: `true or true`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case006",
			query: `false and false`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case007",
			query: `false and true`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case008",
			query: `true and false`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case009",
			query: `true and true`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case010",
			query: `$not(false)`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case011",
			query: `$not(true)`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case012",
			query: `and=1 and or=2`,
			data:  map[string]interface{}{`and`: 1, `or`: 2},

			expected: true,
		},

		{
			name:  "case013",
			query: `and>1 or or<=2`,
			data:  map[string]interface{}{`and`: 1, `or`: 2},

			expected: true,
		},

		{
			name:  "case014",
			query: `and>1 or or!=2`,
			data:  map[string]interface{}{`and`: 1, `or`: 2},

			expected: false,
		},

		{
			name:  "case015",
			query: `and and and`,
			data:  map[string]interface{}{`and`: 1, `or`: 2},

			expected: true,
		},

		{
			name:  "case016",
			query: `$[].content.origin.$lowercase(name)`,
			data:  []interface{}{map[string]interface{}{`content`: map[string]interface{}{`origin`: map[string]interface{}{`name`: `fakeIntegrationName`}}}},

			expected: []interface{}{`fakeintegrationname`},
		},

		{
			name:  "case017",
			query: `true or foo`,
			data:  `null`,

			expected: true,
		},

		{
			name:  "case018",
			query: `foo or true`,
			data:  `null`,

			expected: true,
		},

		{
			name:  "case019",
			query: `false or foo`,
			data:  `null`,

			expected: false,
		},

		{
			name:  "case020",
			query: `foo or false`,
			data:  `null`,

			expected: false,
		},

		{
			name:  "case021",
			query: `foo or bar`,
			data:  `null`,

			expected: false,
		},

		{
			name:  "case022",
			query: `true and foo`,
			data:  `null`,

			expected: false,
		},

		{
			name:  "case023",
			query: `foo and true`,
			data:  `null`,

			expected: false,
		},

		{
			name:  "case024",
			query: `false and foo`,
			data:  `null`,

			expected: false,
		},

		{
			name:  "case025",
			query: `foo and false`,
			data:  `null`,

			expected: false,
		},

		{
			name:  "case026",
			query: `foo and bar`,
			data:  `null`,

			expected: false,
		},

		{
			name:  "case027",
			query: `$not(nothing)`,
			data:  map[string]interface{}{},

			expected: nil,
		},

		{
			name:  "case028",
			query: `foo = '' or $number(foo) = 0`,
			data:  map[string]interface{}{`foo`: ``},

			expected: true,
		},

		{
			name:  "case029",
			query: `$type(data) = 'number' and data > 10`,
			data:  map[string]interface{}{`data`: `15`},

			expected: false,
		},

		{
			name:  "case030",
			query: `$type(age) = 'number' or $number(age) > 0`,
			data:  map[string]interface{}{`age`: `33 1/2`},

			shouldError: true,
			errorCode:   "D3030",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Parse expression
			expr, err := parser.Parse(tc.query)
			if err != nil {
				if tc.shouldError {
					// Expected error during parsing
					return
				}
				t.Fatalf("Parse error: %v", err)
			}

			// Evaluate
			ev := evaluator.New()
			var result interface{}

			if tc.bindings != nil {
				result, err = ev.EvalWithBindings(context.Background(), expr, tc.data, tc.bindings)
			} else {
				result, err = ev.Eval(context.Background(), expr, tc.data)
			}

			// Check error expectation
			if tc.shouldError {
				if err == nil {
					t.Errorf("Expected error but got result: %v", result)
				}
				// TODO: Check error code when error types are implemented
				return
			}

			if err != nil {
				t.Fatalf("Eval error: %v", err)
			}

			// Compare results (basic comparison for now)
			// TODO: Implement proper deep comparison with JSONata semantics
			if !compareResults(result, tc.expected) {
				t.Errorf("Result mismatch\nGot:      %v\nExpected: %v", result, tc.expected)
			}
		})
	}
}
