// Code generated by importer. DO NOT EDIT.
// Source: thirdy/jsonata/test/test-suite/groups/comparison-operators

package imported_test

import (
	"context"
	"testing"

	"github.com/sandrolain/gosonata/pkg/evaluator"
	"github.com/sandrolain/gosonata/pkg/parser"
)

// TestComparisonOperators runs 29 test cases from the official JSONata test suite.
// Group: comparison-operators
func TestComparisonOperators(t *testing.T) {
	testCases := []struct {
		name        string
		query       string
		data        interface{}
		bindings    map[string]interface{}
		expected    interface{}
		shouldError bool
		errorCode   string
	}{

		{
			name:  "case000",
			query: `3>-3`,
			data:  nil,

			expected: true,
		},

		{
			name:  "case001",
			query: `3>3`,
			data:  nil,

			expected: false,
		},

		{
			name:  "case002",
			query: `3=3`,
			data:  nil,

			expected: true,
		},

		{
			name:  "case003",
			query: `"3"="3"`,
			data:  nil,

			expected: true,
		},

		{
			name:  "case004",
			query: `"3"=3`,
			data:  nil,

			expected: false,
		},

		{
			name:  "case005",
			query: `"hello" = "hello"`,
			data:  nil,

			expected: true,
		},

		{
			name:  "case006",
			query: `"hello" != "world"`,
			data:  nil,

			expected: true,
		},

		{
			name:  "case007",
			query: `"hello" < "world"`,
			data:  nil,

			expected: true,
		},

		{
			name:  "case008",
			query: `"32" < 42`,
			data:  nil,

			shouldError: true,
			errorCode:   "T2009",
		},

		{
			name:  "case009",
			query: `null <= "world"`,
			data:  nil,

			shouldError: true,
			errorCode:   "T2010",
		},

		{
			name:  "case010",
			query: `3 >= true`,
			data:  nil,

			shouldError: true,
			errorCode:   "T2010",
		},

		{
			name:  "case011",
			query: `foo.bar > bar`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case012",
			query: `foo.bar >= bar`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case013",
			query: `foo.bar<bar`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case014",
			query: `foo.bar<=bar`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case015",
			query: `bar>foo.bar`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case016",
			query: `bar < foo.bar`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case017",
			query: `foo.bar = bar`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case018",
			query: `foo.bar!= bar`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case019",
			query: `bar = foo.bar + 56`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: true,
		},

		{
			name:  "case020",
			query: `bar !=foo.bar + 56`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: false,
		},

		{
			name:  "case021",
			query: `foo.blah.baz[fud = "hello"]`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: map[string]interface{}{`fud`: `hello`},
		},

		{
			name:  "case022",
			query: `foo.blah.baz[fud != "world"]`,
			data:  map[string]interface{}{`bar`: 98, `foo`: map[string]interface{}{`bar`: 42, `blah`: []interface{}{map[string]interface{}{`baz`: map[string]interface{}{`fud`: `hello`}}, map[string]interface{}{`baz`: map[string]interface{}{`fud`: `world`}}, map[string]interface{}{`bazz`: `gotcha`}}, `blah.baz`: `here`}},

			expected: map[string]interface{}{`fud`: `hello`},
		},

		{
			name:  "case023",
			query: `Account.Order.Product[Price > 30].Price`,
			data:  map[string]interface{}{`Account`: map[string]interface{}{`Account Name`: `Firefly`, `Order`: []interface{}{map[string]interface{}{`OrderID`: `order103`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 2, `SKU`: `0406654608`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Orange`, `Depth`: 210, `Height`: 200, `Weight`: 0.6, `Width`: 300}, `Price`: 21.67, `Product Name`: `Trilby hat`, `ProductID`: 858236, `Quantity`: 1, `SKU`: `0406634348`}}}, map[string]interface{}{`OrderID`: `order104`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 4, `SKU`: `040657863`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Black`, `Depth`: 210, `Height`: 20, `Weight`: 2, `Width`: 30}, `Price`: 107.99, `Product Name`: `Cloak`, `ProductID`: 345664, `Quantity`: 1, `SKU`: `0406654603`}}}}}},

			expected: []interface{}{34.45, 34.45, 107.99},
		},

		{
			name:  "case024",
			query: `Account.Order.Product.Price[$<=35]`,
			data:  map[string]interface{}{`Account`: map[string]interface{}{`Account Name`: `Firefly`, `Order`: []interface{}{map[string]interface{}{`OrderID`: `order103`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 2, `SKU`: `0406654608`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Orange`, `Depth`: 210, `Height`: 200, `Weight`: 0.6, `Width`: 300}, `Price`: 21.67, `Product Name`: `Trilby hat`, `ProductID`: 858236, `Quantity`: 1, `SKU`: `0406634348`}}}, map[string]interface{}{`OrderID`: `order104`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 4, `SKU`: `040657863`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Black`, `Depth`: 210, `Height`: 20, `Weight`: 2, `Width`: 30}, `Price`: 107.99, `Product Name`: `Cloak`, `ProductID`: 345664, `Quantity`: 1, `SKU`: `0406654603`}}}}}},

			expected: []interface{}{34.45, 21.67, 34.45},
		},

		{
			name:  "case025",
			query: `false > 1`,
			data:  map[string]interface{}{},

			shouldError: true,
			errorCode:   "T2010",
		},

		{
			name:  "case026",
			query: `false > $x`,
			data:  map[string]interface{}{},

			shouldError: true,
			errorCode:   "T2010",
		},

		{
			name:  "case027",
			query: `3 > $x`,
			data:  map[string]interface{}{},

			expected: nil,
		},

		{
			name:  "case028",
			query: `$x <= 'hello'`,
			data:  map[string]interface{}{},

			expected: nil,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Parse expression
			expr, err := parser.Parse(tc.query)
			if err != nil {
				if tc.shouldError {
					// Expected error during parsing
					return
				}
				t.Fatalf("Parse error: %v", err)
			}

			// Evaluate
			ev := evaluator.New()
			var result interface{}

			if tc.bindings != nil {
				result, err = ev.EvalWithBindings(context.Background(), expr, tc.data, tc.bindings)
			} else {
				result, err = ev.Eval(context.Background(), expr, tc.data)
			}

			// Check error expectation
			if tc.shouldError {
				if err == nil {
					t.Errorf("Expected error but got result: %v", result)
				}
				// TODO: Check error code when error types are implemented
				return
			}

			if err != nil {
				t.Fatalf("Eval error: %v", err)
			}

			// Compare results (basic comparison for now)
			// TODO: Implement proper deep comparison with JSONata semantics
			if !compareResults(result, tc.expected) {
				t.Errorf("Result mismatch\nGot:      %v\nExpected: %v", result, tc.expected)
			}
		})
	}
}
