// Code generated by importer. DO NOT EDIT.
// Source: thirdy/jsonata/test/test-suite/groups/function-count

package imported_test

import (
	"context"
	"testing"

	"github.com/sandrolain/gosonata/pkg/evaluator"
	"github.com/sandrolain/gosonata/pkg/parser"
)

// TestFunctionCount runs 14 test cases from the official JSONata test suite.
// Group: function-count
func TestFunctionCount(t *testing.T) {
	testCases := []struct {
		name        string
		query       string
		data        interface{}
		bindings    map[string]interface{}
		expected    interface{}
		shouldError bool
		errorCode   string
	}{

		{
			name:  "case000",
			query: `$count(Account.Order.Product.(Price * Quantity))`,
			data:  map[string]interface{}{`Account`: map[string]interface{}{`Account Name`: `Firefly`, `Order`: []interface{}{map[string]interface{}{`OrderID`: `order103`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 2, `SKU`: `0406654608`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Orange`, `Depth`: 210, `Height`: 200, `Weight`: 0.6, `Width`: 300}, `Price`: 21.67, `Product Name`: `Trilby hat`, `ProductID`: 858236, `Quantity`: 1, `SKU`: `0406634348`}}}, map[string]interface{}{`OrderID`: `order104`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 4, `SKU`: `040657863`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Black`, `Depth`: 210, `Height`: 20, `Weight`: 2, `Width`: 30}, `Price`: 107.99, `Product Name`: `Cloak`, `ProductID`: 345664, `Quantity`: 1, `SKU`: `0406654603`}}}}}},

			expected: 4,
		},

		{
			name:  "case001",
			query: `Account.Order.$count(Product.(Price * Quantity))`,
			data:  map[string]interface{}{`Account`: map[string]interface{}{`Account Name`: `Firefly`, `Order`: []interface{}{map[string]interface{}{`OrderID`: `order103`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 2, `SKU`: `0406654608`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Orange`, `Depth`: 210, `Height`: 200, `Weight`: 0.6, `Width`: 300}, `Price`: 21.67, `Product Name`: `Trilby hat`, `ProductID`: 858236, `Quantity`: 1, `SKU`: `0406634348`}}}, map[string]interface{}{`OrderID`: `order104`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 4, `SKU`: `040657863`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Black`, `Depth`: 210, `Height`: 20, `Weight`: 2, `Width`: 30}, `Price`: 107.99, `Product Name`: `Cloak`, `ProductID`: 345664, `Quantity`: 1, `SKU`: `0406654603`}}}}}},

			expected: []interface{}{2, 2},
		},

		{
			name:  "case002",
			query: `Account.Order.(OrderID & ": " & $count(Product.(Price*Quantity)))`,
			data:  map[string]interface{}{`Account`: map[string]interface{}{`Account Name`: `Firefly`, `Order`: []interface{}{map[string]interface{}{`OrderID`: `order103`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 2, `SKU`: `0406654608`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Orange`, `Depth`: 210, `Height`: 200, `Weight`: 0.6, `Width`: 300}, `Price`: 21.67, `Product Name`: `Trilby hat`, `ProductID`: 858236, `Quantity`: 1, `SKU`: `0406634348`}}}, map[string]interface{}{`OrderID`: `order104`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 4, `SKU`: `040657863`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Black`, `Depth`: 210, `Height`: 20, `Weight`: 2, `Width`: 30}, `Price`: 107.99, `Product Name`: `Cloak`, `ProductID`: 345664, `Quantity`: 1, `SKU`: `0406654603`}}}}}},

			expected: []interface{}{`order103: 2`, `order104: 2`},
		},

		{
			name:  "case003",
			query: `$count([])`,
			data:  nil,

			expected: 0,
		},

		{
			name:  "case004",
			query: `$count([1,2,3])`,
			data:  nil,

			expected: 3,
		},

		{
			name:  "case005",
			query: `$count(["1","2","3"])`,
			data:  nil,

			expected: 3,
		},

		{
			name:  "case006",
			query: `$count(["1","2",3])`,
			data:  nil,

			expected: 3,
		},

		{
			name:  "case007",
			query: `$count(1)`,
			data:  nil,

			expected: 1,
		},

		{
			name:  "case008",
			query: `$count([],[])`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case009",
			query: `$count([1,2,3],[])`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case010",
			query: `$count([],[],[])`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case011",
			query: `$count([1,2],[],[])`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case012",
			query: `$count(undefined)`,
			data:  nil,

			expected: 0,
		},

		{
			name:  "case013",
			query: `$count([1,2,3,4]) / 2`,
			data:  nil,

			expected: 2,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Parse expression
			expr, err := parser.Parse(tc.query)
			if err != nil {
				if tc.shouldError {
					// Expected error during parsing
					return
				}
				t.Fatalf("Parse error: %v", err)
			}

			// Evaluate
			ev := evaluator.New()
			var result interface{}

			if tc.bindings != nil {
				result, err = ev.EvalWithBindings(context.Background(), expr, tc.data, tc.bindings)
			} else {
				result, err = ev.Eval(context.Background(), expr, tc.data)
			}

			// Check error expectation
			if tc.shouldError {
				if err == nil {
					t.Errorf("Expected error but got result: %v", result)
				}
				// TODO: Check error code when error types are implemented
				return
			}

			if err != nil {
				t.Fatalf("Eval error: %v", err)
			}

			// Compare results (basic comparison for now)
			// TODO: Implement proper deep comparison with JSONata semantics
			if !compareResults(result, tc.expected) {
				t.Errorf("Result mismatch\nGot:      %v\nExpected: %v", result, tc.expected)
			}
		})
	}
}
