// Code generated by importer. DO NOT EDIT.
// Source: thirdy/jsonata/test/test-suite/groups/function-replace

package imported_test

import (
	"context"
	"testing"

	"github.com/sandrolain/gosonata/pkg/evaluator"
	"github.com/sandrolain/gosonata/pkg/parser"
)

// TestFunctionReplace runs 12 test cases from the official JSONata test suite.
// Group: function-replace
func TestFunctionReplace(t *testing.T) {
	testCases := []struct {
		name        string
		query       string
		data        interface{}
		bindings    map[string]interface{}
		expected    interface{}
		shouldError bool
		errorCode   string
	}{

		{
			name:  "case000",
			query: `$replace("Hello World", "World", "Everyone")`,
			data:  nil,

			expected: `Hello Everyone`,
		},

		{
			name:  "case001",
			query: `$replace("the cat sat on the mat", "at", "it")`,
			data:  nil,

			expected: `the cit sit on the mit`,
		},

		{
			name:  "case002",
			query: `$replace("the cat sat on the mat", "at", "it", 0)`,
			data:  nil,

			expected: `the cat sat on the mat`,
		},

		{
			name:  "case003",
			query: `$replace("the cat sat on the mat", "at", "it", 2)`,
			data:  nil,

			expected: `the cit sit on the mat`,
		},

		{
			name:  "case004",
			query: `$replace(nothing, "at", "it", 2)`,
			data:  nil,

			expected: nil,
		},

		{
			name:  "case005",
			query: `$replace("hello")`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case006",
			query: `$replace("hello", "l", "1", null)`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case007",
			query: `$replace("hello", "l", "1", -2)`,
			data:  nil,

			shouldError: true,
			errorCode:   "D3011",
		},

		{
			name:  "case008",
			query: `$replace("hello", 1)`,
			data:  `hello`,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case009",
			query: `$replace("hello", "", "bye")`,
			data:  nil,

			shouldError: true,
			errorCode:   "D3010",
		},

		{
			name:  "case010",
			query: `$replace("hello", 2, 1)`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case011",
			query: `$replace(123, 2, 1)`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Parse expression
			expr, err := parser.Parse(tc.query)
			if err != nil {
				if tc.shouldError {
					// Expected error during parsing
					return
				}
				t.Fatalf("Parse error: %v", err)
			}

			// Evaluate
			ev := evaluator.New()
			var result interface{}

			if tc.bindings != nil {
				result, err = ev.EvalWithBindings(context.Background(), expr, tc.data, tc.bindings)
			} else {
				result, err = ev.Eval(context.Background(), expr, tc.data)
			}

			// Check error expectation
			if tc.shouldError {
				if err == nil {
					t.Errorf("Expected error but got result: %v", result)
				}
				// TODO: Check error code when error types are implemented
				return
			}

			if err != nil {
				t.Fatalf("Eval error: %v", err)
			}

			// Compare results (basic comparison for now)
			// TODO: Implement proper deep comparison with JSONata semantics
			if !compareResults(result, tc.expected) {
				t.Errorf("Result mismatch\nGot:      %v\nExpected: %v", result, tc.expected)
			}
		})
	}
}
