// Code generated by importer. DO NOT EDIT.
// Source: thirdy/jsonata/test/test-suite/groups/function-number

package imported_test

import (
	"context"
	"testing"

	"github.com/sandrolain/gosonata/pkg/evaluator"
	"github.com/sandrolain/gosonata/pkg/parser"
)

// TestFunctionNumber runs 34 test cases from the official JSONata test suite.
// Group: function-number
func TestFunctionNumber(t *testing.T) {
	testCases := []struct {
		name        string
		query       string
		data        interface{}
		bindings    map[string]interface{}
		expected    interface{}
		shouldError bool
		errorCode   string
	}{

		{
			name:  "case000",
			query: `$number(0)`,
			data:  nil,

			expected: 0,
		},

		{
			name:  "case001",
			query: `$number(10)`,
			data:  nil,

			expected: 10,
		},

		{
			name:  "case002",
			query: `$number(-0.05)`,
			data:  nil,

			expected: -0.05,
		},

		{
			name:  "case003",
			query: `$number("0")`,
			data:  nil,

			expected: 0,
		},

		{
			name:  "case004",
			query: `$number("-0.05")`,
			data:  nil,

			expected: -0.05,
		},

		{
			name:  "case005",
			query: `$number("1e2")`,
			data:  nil,

			expected: 100,
		},

		{
			name:  "case006",
			query: `$number("1.0e-2")`,
			data:  nil,

			expected: 0.01,
		},

		{
			name:  "case007",
			query: `$number("1e0")`,
			data:  nil,

			expected: 1,
		},

		{
			name:  "case008",
			query: `$number("10e500")`,
			data:  nil,

			shouldError: true,
			errorCode:   "D3030",
		},

		{
			name:  "case009",
			query: `$number("Hello world")`,
			data:  nil,

			shouldError: true,
			errorCode:   "D3030",
		},

		{
			name:  "case010",
			query: `$number("1/2")`,
			data:  nil,

			shouldError: true,
			errorCode:   "D3030",
		},

		{
			name:  "case011",
			query: `$number("1234 hello")`,
			data:  nil,

			shouldError: true,
			errorCode:   "D3030",
		},

		{
			name:  "case012",
			query: `$number("")`,
			data:  nil,

			shouldError: true,
			errorCode:   "D3030",
		},

		{
			name:  "case013",
			query: `$number(true)`,
			data:  nil,

			expected: 1,
		},

		{
			name:  "case014",
			query: `$number(false)`,
			data:  nil,

			expected: 0,
		},

		{
			name:  "case015",
			query: `$number(Account.blah)`,
			data:  map[string]interface{}{`Account`: map[string]interface{}{`Account Name`: `Firefly`, `Order`: []interface{}{map[string]interface{}{`OrderID`: `order103`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 2, `SKU`: `0406654608`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Orange`, `Depth`: 210, `Height`: 200, `Weight`: 0.6, `Width`: 300}, `Price`: 21.67, `Product Name`: `Trilby hat`, `ProductID`: 858236, `Quantity`: 1, `SKU`: `0406634348`}}}, map[string]interface{}{`OrderID`: `order104`, `Product`: []interface{}{map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Purple`, `Depth`: 210, `Height`: 200, `Weight`: 0.75, `Width`: 300}, `Price`: 34.45, `Product Name`: `Bowler Hat`, `ProductID`: 858383, `Quantity`: 4, `SKU`: `040657863`}, map[string]interface{}{`Description`: map[string]interface{}{`Colour`: `Black`, `Depth`: 210, `Height`: 20, `Weight`: 2, `Width`: 30}, `Price`: 107.99, `Product Name`: `Cloak`, `ProductID`: 345664, `Quantity`: 1, `SKU`: `0406654603`}}}}}},

			expected: nil,
		},

		{
			name:  "case016",
			query: `$number(null)`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case017",
			query: `$number([])`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case018",
			query: `$number("[1]")`,
			data:  nil,

			shouldError: true,
			errorCode:   "D3030",
		},

		{
			name:  "case019",
			query: `$number([1,2])`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case020",
			query: `$number(["hello"])`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case021",
			query: `$number(["2"])`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case022",
			query: `$number({})`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case023",
			query: `$number({"hello":"world"})`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case024",
			query: `$number($number)`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case025",
			query: `$number(function(){5})`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case026",
			query: `$number(1,2)`,
			data:  nil,

			shouldError: true,
			errorCode:   "T0410",
		},

		{
			name:  "case027",
			query: `$number('00')`,
			data:  nil,

			expected: 0,
		},

		{
			name:  "case028",
			query: `$number('0123')`,
			data:  nil,

			expected: 123,
		},

		{
			name:  "case029",
			query: `$number('-007')`,
			data:  nil,

			expected: -7,
		},

		{
			name:  "case030",
			query: `$number('000.00123000')`,
			data:  nil,

			expected: 0.00123,
		},

		{
			name:  "case031",
			query: `$number('0x12')`,
			data:  nil,

			expected: 18,
		},

		{
			name:  "case032",
			query: `$number('0B101')`,
			data:  nil,

			expected: 5,
		},

		{
			name:  "case033",
			query: `$number('0O12')`,
			data:  nil,

			expected: 10,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Parse expression
			expr, err := parser.Parse(tc.query)
			if err != nil {
				if tc.shouldError {
					// Expected error during parsing
					return
				}
				t.Fatalf("Parse error: %v", err)
			}

			// Evaluate
			ev := evaluator.New()
			var result interface{}

			if tc.bindings != nil {
				result, err = ev.EvalWithBindings(context.Background(), expr, tc.data, tc.bindings)
			} else {
				result, err = ev.Eval(context.Background(), expr, tc.data)
			}

			// Check error expectation
			if tc.shouldError {
				if err == nil {
					t.Errorf("Expected error but got result: %v", result)
				}
				// TODO: Check error code when error types are implemented
				return
			}

			if err != nil {
				t.Fatalf("Eval error: %v", err)
			}

			// Compare results (basic comparison for now)
			// TODO: Implement proper deep comparison with JSONata semantics
			if !compareResults(result, tc.expected) {
				t.Errorf("Result mismatch\nGot:      %v\nExpected: %v", result, tc.expected)
			}
		})
	}
}
