// Code generated by importer. DO NOT EDIT.

package imported_test

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
)

// compareResults compares two results (simplified version).
// TODO: Implement proper comparison with float epsilon, array/object deep equal, etc.
func compareResults(got, expected interface{}) bool {
	gotJSON, err := json.Marshal(got)
	if err != nil {
		return false
	}
	expJSON, err := json.Marshal(expected)
	if err != nil {
		return false
	}

	var gotVal interface{}
	var expVal interface{}
	if err := json.Unmarshal(gotJSON, &gotVal); err != nil {
		return false
	}
	if err := json.Unmarshal(expJSON, &expVal); err != nil {
		return false
	}

	return reflect.DeepEqual(gotVal, expVal)
}

// compareResultsUnordered compares two results, treating arrays as unordered sets.
func compareResultsUnordered(got, expected interface{}) bool {
	// If both are arrays, sort them and compare
	if gotArr, ok := got.([]interface{}); ok {
		if expArr, ok := expected.([]interface{}); ok {
			if len(gotArr) != len(expArr) {
				return false
			}
			// Convert to strings for sorting and comparison
			gotStrs := make([]string, len(gotArr))
			expStrs := make([]string, len(expArr))
			for i, v := range gotArr {
				b, _ := json.Marshal(v)
				gotStrs[i] = string(b)
			}
			for i, v := range expArr {
				b, _ := json.Marshal(v)
				expStrs[i] = string(b)
			}
			sort.Strings(gotStrs)
			sort.Strings(expStrs)
			for i := 0; i < len(gotStrs); i++ {
				if gotStrs[i] != expStrs[i] {
					return false
				}
			}
			return true
		}
	}
	// Otherwise use regular comparison
	return compareResults(got, expected)
}

// formatResultForTest returns a formatted JSON string for test output.
func formatResultForTest(v interface{}) string {
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("%v", v)
	}
	return string(b)
}

// formatExpectedForTest returns a formatted JSON string for test output.
func formatExpectedForTest(v interface{}) string {
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("%v", v)
	}
	return string(b)
}
