// Code generated by importer. DO NOT EDIT.

package imported_test

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// compareResults compares two results (simplified version).
// TODO: Implement proper comparison with float epsilon, array/object deep equal, etc.
func compareResults(got, expected interface{}) bool {
	gotJSON, err := json.Marshal(got)
	if err != nil {
		return false
	}
	expJSON, err := json.Marshal(expected)
	if err != nil {
		return false
	}

	var gotVal interface{}
	var expVal interface{}
	if err := json.Unmarshal(gotJSON, &gotVal); err != nil {
		return false
	}
	if err := json.Unmarshal(expJSON, &expVal); err != nil {
		return false
	}

	return reflect.DeepEqual(gotVal, expVal)
}

// formatResultForTest returns a formatted JSON string for test output.
func formatResultForTest(v interface{}) string {
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("%v", v)
	}
	return string(b)
}

// formatExpectedForTest returns a formatted JSON string for test output.
func formatExpectedForTest(v interface{}) string {
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("%v", v)
	}
	return string(b)
}
